### ISSUE TITLE
Hunt for edge cases

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#30]
`learnr` tutorial chunks to show inconsistencies (aka bugs)

- [ ] #33 Remove `~` when returning unpiped result 
- [ ] Add line breaks before and after code unpipe (https://github.com/rstudio-education/grader/issues/30#issuecomment-509682993)
- [x] #28 Always comes back correct. It seems to not parse arguments after the `:` column slicing. But seems the pipe is also involved. (https://github.com/rstudio-education/grader/issues/30#issuecomment-509684496)
- [ ] Piping to identity is inconsistent between pipelines and ggplot2 (https://github.com/rstudio-education/grader/issues/30#issuecomment-509705078)
- [ ] keywords in functions are returned when a mistake is found, even if kwargs are not passed and values are only passed by position. (https://github.com/rstudio-education/grader/issues/30#issuecomment-511560589)
- [x] #36 Something is causing `learnr`/`grader` to take a long time (and also fail) (https://github.com/rstudio-education/grader/issues/30#issuecomment-511596151)
- [ ] `check_code` can see if a function definition is correct, but if they differ it will fail (expected to return error message) (https://github.com/rstudio-education/grader/issues/30#issuecomment-511607608)
- [ ] Should `check_code` evaluate the call? Or should it be comparing the call? (https://github.com/rstudio-education/grader/issues/30#issuecomment-512006143)

**Comment by chendaniely** [comment]
- [ ] Remove `~` when returning unpiped result
- [ ] Add line breaks before and after code unpipe

````
```{r tidyr1, exercise = TRUE}
library(tidyr)

who %>%
  gather(key, value, new_sp_m014:newrel_f65, na.rm = TRUE)
```


```{r tidyr1-solution}
who %>%
  gather(key, value, new_sp_m014:newrel_f65, na.rm = TRUE)
```

```{r tidyr1-check}
grader::check_code()
```
````

Returns:


> I see that you are using pipe operators (e.g. %>%), so I want to let you know that this is how I am interpretting your code before I check it: ~gather(who, key, value, new_sp_m014:newrel_f65, na.rm = FALSE) I expected na.rm = TRUE where you wrote na.rm = FALSE. Try it again. I have a good feeling about this.

**Comment by chendaniely** [comment]
- [ ] Always comes back correct, seems to be a problem with the `:`? (this behavior has been hard to isoloate)

````
```{r gather-narm-true, exercise=TRUE}
tidyr::gather(who, key, value, new_sp_m014:newrel_f65, na.rm = FALSE)
```

```{r gather-narm-true-solution}
tidyr::gather(who, key, value, new_sp_m014:newrel_f65, na.rm = TRUE)
```

```{r gather-narm-true-check}
grader::check_code()
```
````

Always reports a `correct` message

**Comment by schloerke** [comment]
So if it's not the last argument, it fails?

**Comment by chendaniely** [comment]
but if you pipe in the dataframe, it works!

**Comment by schloerke** [comment]
That is run through `depipe`... what's the difference in the output of `depipe` and the regular input?

**Comment by chendaniely** [comment]
There is a 'sort' in after `unpipe` to arrange the calls and parameters, it's probably something to do with that

**Comment by chendaniely** [comment]
- [ ] keywords in functions are returned when a mistake is found, even if kwargs are not passed and values are only passed by position.

This is probably not a bug, but it's worth pointing out for discussion

![image](https://user-images.githubusercontent.com/5782147/61247378-cd25ea80-a705-11e9-8f93-44f853173fd5.png)

**Comment by chendaniely** [comment]
- [ ] Something is causing `learnr`/`grader` to take a long time (and also fail) #36

**Comment by chendaniely** [comment]
````
```{r aoqqmwwnkvzikirk, exercise = TRUE}
# student code
extract_week <- function(string) {
  as.numeric(stringr::str_extract('x72nd.week', '\\d+'))
}
```

```{r aoqqmwwnkvzikirk-hint-1}
# hint text

```

```{r aoqqmwwnkvzikirk-hint-2}
# hint text

```

```{r aoqqmwwnkvzikirk-solution}
# solution code
extract_week <- function(string) {
  as.numeric(stringr::str_extract('x72nd.week', '\\d+'))
}
```

```{r aoqqmwwnkvzikirk-check}
# check code
grader::check_code()
```
````

**Comment by chendaniely** [comment]
The below block creates an exercise where the student uses `spread` instead of `gather`.
The error/message in `learnr` is "Strings must match column names. Unknown columns: week".
This is the error message given from the student

1. Using the wrong function (`spread` instead of `gather`)
2. Passing the wrong parameters to `spread`

Should `grader::check_code` be executing code? or just comparing the calls?

In this example shold the message be "expected gather where you wrote spread"?

````
```{r}
billboard <- readr::read_csv("https://raw.githubusercontent.com/hadley/tidy-data/master/data/billboard.csv")
```

```{r ebepjqxhskvqnspn, exercise = TRUE}
library(tidyr)

billboard_tidy <- spread(billboard, "week", "rank", x1st.week:x76th.week)
```

```{r ebepjqxhskvqnspn-hint-1}
# hint text
"Use the gather function from tidyr"
```

```{r ebepjqxhskvqnspn-hint-2}
# hint text
"You can use tidyselect notation to select the columns, e.g., col1:col76"
```

```{r ebepjqxhskvqnspn-solution}
# solution code
billboard_tidy <- gather(billboard, "week", "rank", x1st.week:x76th.week)
```

```{r ebepjqxhskvqnspn-check}
# check code
grader::check_code()
```

````

**Comment by gadenbuie** [comment]
As far as I can tell, this work has all been completed or addressed elsewhere
